const types = {
  SNACKBAR_ALERT: "SNACKBAR_ALERT",
  SET_API_KEy: "SET_API_KEY",
  SET_CHAT_LIST: "SET_CHAT_LIST",
  SET_NEW_CHAT: "SET_NEW_CHAT",
  SET_ACTIVE_CHAT: "SET_ACTIVE_CHAT",
  SET_THINKING: "SET_THINKING",
  SET_ACTIVE_CHAT_MESSAGE: "SET_ACTIVE_CHAT_MESSAGE",
};
export default types;
